---
# Guest machine config
guest_vagrant_dir: /var/www/vagrant

# VM general config
vm_box: geerlingguy/centos6
vm_ip: 10.0.0.10
vm_name: wordpressvm
vm_hostname: wordpress.vm

# WordPress config
wp_version: latest
wp_site_title: WordPress Site
wp_project_dir_name: wordpress
wp_admin_user: admin
wp_admin_pass: admin
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_pass: wordpress
# Define list of plugins to be installed
wp_plugins:
  - { name: akismet, version: 3.3, install: false }
